### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Exited with code 1     at ChildProcess.<anonymous> (/Users/xxx/WorkSpace/Case_Minder_Vue/node_modules/opn/index.js:83:13)

### ISSUE THREAD

**Issue by CYsuncheng** [MeYoung/Case_Minder_Vue#1]
npm run dev 遇到此问题，尝试了切换node的版本，8.x和15.x，都不行

Entrypoint app = app.js app.js.map
[0] multi ./build/dev-client ./src/main.js 40 bytes {app} [built]
[./build/dev-client.js] 245 bytes {app} [built]
[./hotbox/hotbox.js] 31.1 KiB {app} [built]
[./kityminder-core/dist/kityminder.core.js] 370 KiB {app} [built]
[./node_modules/codemirror/addon/mode/overlay.js] 3.17 KiB {app} [built]
[./node_modules/codemirror/lib/codemirror.js] 389 KiB {app} [built]
[./node_modules/codemirror/mode/css/css.js] 39.5 KiB {app} [built]
[./node_modules/codemirror/mode/gfm/gfm.js] 4.98 KiB {app} [built]
[./node_modules/codemirror/mode/htmlmixed/htmlmixed.js] 5.55 KiB {app} [built]
[./node_modules/codemirror/mode/javascript/javascript.js] 37 KiB {app} [built]
[./node_modules/codemirror/mode/xml/xml.js] 12.9 KiB {app} [built]
[./node_modules/element-ui/lib/element-ui.common.js] 1.1 MiB {app} [built]
[./node_modules/element-ui/lib/theme-chalk/index.css] 1.02 KiB {app} [built]
[./node_modules/eventsource-polyfill/dist/browserify-eventsource.js] 852 bytes {app} [built]
[./src/main.js] 1.18 KiB {app} [built]
    + 500 hidden modules
Child html-webpack-plugin for "index.html":
         Asset     Size  Chunks  Chunk Names
    index.html  536 KiB       0
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./index.html] 479 bytes {0} [built]
    [./node_modules/html-webpack-plugin/node_modules/lodash/lodash.js] 530 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
ℹ ｢wdm｣: Compiled successfully.
> 监听端口为 http://::1:8088

(node:42252) UnhandledPromiseRejectionWarning: Error: Exited with code 1
    at ChildProcess.<anonymous> (/Users/xxx/WorkSpace/Case_Minder_Vue/node_modules/opn/index.js:83:13)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:915:16)
    at Socket.stream.socket.on (internal/child_process.js:336:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:561:12)
(node:42252) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)
(node:42252) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js processwith a non-zero exit code.

**Comment by CYsuncheng** [comment]
只是报了这个错误，但是不影响使用
